{
 "title": "Degen",
 "time": { "from": "2024-11-22T06:22:30.000Z", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "asset",
    "query": {
     "query": "label_values(asset_balance{asset!=\"IDR\"},asset)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$asset midprice ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asset_midprice{asset=\"$asset-IDR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Position average price",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "position_average_price{asset=\"$asset-IDR\"}",
     "legendFormat": "IDR"
    }
   ]
  },
  {
   "title": "Position Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "position_size{asset=\"$asset-IDR\"}",
     "legendFormat": "{{$asset}}"
    }
   ]
  },
  {
   "title": "$asset orderbook spread",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "price_spread{asset=\"$asset-IDR\"}/0.0001",
     "legendFormat": "BiPs"
    }
   ]
  },
  {
   "title": "IDR balance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "asset_balance{asset=\"IDR\"}",
     "legendFormat": "{{asset}}"
    }
   ]
  },
  {
   "title": "$asset balance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "asset_balance{asset=\"$asset\"} ",
     "legendFormat": "{{asset}}"
    }
   ]
  },
  {
   "title": "Notional balance for pair",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "targets": [
    {
     "expr": "sum(asset_balance{asset=\"$asset\"}) * sum(asset_midprice{asset=\"$asset-IDR\"}) + sum(asset_balance{asset=\"IDR\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg request durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(request_duration_seconds_sum[$__rate_interval])/rate(request_duration_seconds_count[$__rate_interval]) ",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Avg place order duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(place_order_duration_seconds_sum[$__rate_interval]) / rate(place_order_duration_seconds_count[$__rate_interval]) ",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Compound PnL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "unrealized_pnl{asset=\"$asset-IDR\"} + realized_pnl{asset=\"$asset-IDR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unrealized PnL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "unrealized_pnl{asset=\"$asset-IDR\"}",
     "legendFormat": "IDR"
    }
   ]
  },
  {
   "title": "Realized PnL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "expr": "realized_pnl{asset=\"$asset-IDR\"}",
     "legendFormat": "IDR"
    }
   ]
  },
  {
   "title": "$asset price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "asset_midprice{asset=\"$asset-IDR\"} ",
     "legendFormat": "Exchange midprice"
    },
    {
     "expr": "position_average_price{asset=\"$asset-IDR\"}",
     "legendFormat": "Position avg price"
    }
   ]
  }
 ]
}