// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package pintupro

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson8536833dDecodeDegenPkgConnectorsPintupro(in *jlexer.Lexer, out *wsMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "request_id":
			out.RequestID = string(in.String())
		case "timestamp":
			out.Timestamp = int64(in.Int64())
		case "method":
			out.Method = string(in.String())
		case "channel":
			out.Channel = string(in.String())
		case "code":
			out.Code = int(in.Int())
		case "message":
			out.Message = string(in.String())
		case "reason":
			out.Reason = string(in.String())
		case "Data":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Data).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro(out *jwriter.Writer, in wsMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"request_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.RequestID))
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.Int64(int64(in.Timestamp))
	}
	{
		const prefix string = ",\"method\":"
		out.RawString(prefix)
		out.String(string(in.Method))
	}
	{
		const prefix string = ",\"channel\":"
		out.RawString(prefix)
		out.String(string(in.Channel))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.Int(int(in.Code))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	{
		const prefix string = ",\"Data\":"
		out.RawString(prefix)
		out.Raw((in.Data).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v wsMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v wsMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *wsMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *wsMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro(l, v)
}
func easyjson8536833dDecodeDegenPkgConnectorsPintupro1(in *jlexer.Lexer, out *tradesMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "trades":
			if in.IsNull() {
				in.Skip()
				out.Trades = nil
			} else {
				in.Delim('[')
				if out.Trades == nil {
					if !in.IsDelim(']') {
						out.Trades = make([]struct {
							Side      string `json:"side"`
							Price     string `json:"price"`
							Size      string `json:"size"`
							Timestamp int64  `json:"timestamp"`
							Symbol    string `json:"symbol"`
						}, 0, 0)
					} else {
						out.Trades = []struct {
							Side      string `json:"side"`
							Price     string `json:"price"`
							Size      string `json:"size"`
							Timestamp int64  `json:"timestamp"`
							Symbol    string `json:"symbol"`
						}{}
					}
				} else {
					out.Trades = (out.Trades)[:0]
				}
				for !in.IsDelim(']') {
					var v1 struct {
						Side      string `json:"side"`
						Price     string `json:"price"`
						Size      string `json:"size"`
						Timestamp int64  `json:"timestamp"`
						Symbol    string `json:"symbol"`
					}
					easyjson8536833dDecode(in, &v1)
					out.Trades = append(out.Trades, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro1(out *jwriter.Writer, in tradesMsg) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"trades\":"
		out.RawString(prefix[1:])
		if in.Trades == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Trades {
				if v2 > 0 {
					out.RawByte(',')
				}
				easyjson8536833dEncode(out, v3)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v tradesMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v tradesMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *tradesMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *tradesMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro1(l, v)
}
func easyjson8536833dDecode(in *jlexer.Lexer, out *struct {
	Side      string `json:"side"`
	Price     string `json:"price"`
	Size      string `json:"size"`
	Timestamp int64  `json:"timestamp"`
	Symbol    string `json:"symbol"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "side":
			out.Side = string(in.String())
		case "price":
			out.Price = string(in.String())
		case "size":
			out.Size = string(in.String())
		case "timestamp":
			out.Timestamp = int64(in.Int64())
		case "symbol":
			out.Symbol = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncode(out *jwriter.Writer, in struct {
	Side      string `json:"side"`
	Price     string `json:"price"`
	Size      string `json:"size"`
	Timestamp int64  `json:"timestamp"`
	Symbol    string `json:"symbol"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"side\":"
		out.RawString(prefix[1:])
		out.String(string(in.Side))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.String(string(in.Price))
	}
	{
		const prefix string = ",\"size\":"
		out.RawString(prefix)
		out.String(string(in.Size))
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.Int64(int64(in.Timestamp))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	out.RawByte('}')
}
func easyjson8536833dDecodeDegenPkgConnectorsPintupro2(in *jlexer.Lexer, out *orderBookMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "symbol":
			out.Symbol = string(in.String())
		case "bids":
			if in.IsNull() {
				in.Skip()
				out.Bids = nil
			} else {
				in.Delim('[')
				if out.Bids == nil {
					if !in.IsDelim(']') {
						out.Bids = make([][]string, 0, 2)
					} else {
						out.Bids = [][]string{}
					}
				} else {
					out.Bids = (out.Bids)[:0]
				}
				for !in.IsDelim(']') {
					var v4 []string
					if in.IsNull() {
						in.Skip()
						v4 = nil
					} else {
						in.Delim('[')
						if v4 == nil {
							if !in.IsDelim(']') {
								v4 = make([]string, 0, 4)
							} else {
								v4 = []string{}
							}
						} else {
							v4 = (v4)[:0]
						}
						for !in.IsDelim(']') {
							var v5 string
							v5 = string(in.String())
							v4 = append(v4, v5)
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Bids = append(out.Bids, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "asks":
			if in.IsNull() {
				in.Skip()
				out.Asks = nil
			} else {
				in.Delim('[')
				if out.Asks == nil {
					if !in.IsDelim(']') {
						out.Asks = make([][]string, 0, 2)
					} else {
						out.Asks = [][]string{}
					}
				} else {
					out.Asks = (out.Asks)[:0]
				}
				for !in.IsDelim(']') {
					var v6 []string
					if in.IsNull() {
						in.Skip()
						v6 = nil
					} else {
						in.Delim('[')
						if v6 == nil {
							if !in.IsDelim(']') {
								v6 = make([]string, 0, 4)
							} else {
								v6 = []string{}
							}
						} else {
							v6 = (v6)[:0]
						}
						for !in.IsDelim(']') {
							var v7 string
							v7 = string(in.String())
							v6 = append(v6, v7)
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Asks = append(out.Asks, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro2(out *jwriter.Writer, in orderBookMsg) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"bids\":"
		out.RawString(prefix)
		if in.Bids == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Bids {
				if v8 > 0 {
					out.RawByte(',')
				}
				if v9 == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v10, v11 := range v9 {
						if v10 > 0 {
							out.RawByte(',')
						}
						out.String(string(v11))
					}
					out.RawByte(']')
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"asks\":"
		out.RawString(prefix)
		if in.Asks == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v12, v13 := range in.Asks {
				if v12 > 0 {
					out.RawByte(',')
				}
				if v13 == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v14, v15 := range v13 {
						if v14 > 0 {
							out.RawByte(',')
						}
						out.String(string(v15))
					}
					out.RawByte(']')
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v orderBookMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v orderBookMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *orderBookMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *orderBookMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro2(l, v)
}
func easyjson8536833dDecodeDegenPkgConnectorsPintupro3(in *jlexer.Lexer, out *Envelope) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "request_id":
			out.RequestID = string(in.String())
		case "timestamp":
			out.Timestamp = int64(in.Int64())
		case "method":
			out.Method = string(in.String())
		case "params":
			if m, ok := out.Params.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Params.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Params = in.Interface()
			}
		case "signature":
			out.Signature = string(in.String())
		case "api_key":
			out.APIKey = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro3(out *jwriter.Writer, in Envelope) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"request_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.RequestID))
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.Int64(int64(in.Timestamp))
	}
	{
		const prefix string = ",\"method\":"
		out.RawString(prefix)
		out.String(string(in.Method))
	}
	{
		const prefix string = ",\"params\":"
		out.RawString(prefix)
		if m, ok := in.Params.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Params.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Params))
		}
	}
	{
		const prefix string = ",\"signature\":"
		out.RawString(prefix)
		out.String(string(in.Signature))
	}
	{
		const prefix string = ",\"api_key\":"
		out.RawString(prefix)
		out.String(string(in.APIKey))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Envelope) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Envelope) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Envelope) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Envelope) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro3(l, v)
}
