// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package pintupro

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	decimal "github.com/shopspring/decimal"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson8536833dDecodeDegenPkgConnectorsPintupro(in *jlexer.Lexer, out *wsMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "request_id":
			out.RequestID = string(in.String())
		case "timestamp":
			out.Timestamp = int64(in.Int64())
		case "method":
			out.Method = string(in.String())
		case "channel":
			out.Channel = string(in.String())
		case "code":
			out.Code = int(in.Int())
		case "message":
			out.Message = string(in.String())
		case "reason":
			out.Reason = string(in.String())
		case "data":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Data).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro(out *jwriter.Writer, in wsMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"request_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.RequestID))
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.Int64(int64(in.Timestamp))
	}
	{
		const prefix string = ",\"method\":"
		out.RawString(prefix)
		out.String(string(in.Method))
	}
	{
		const prefix string = ",\"channel\":"
		out.RawString(prefix)
		out.String(string(in.Channel))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.Int(int(in.Code))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.Raw((in.Data).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v wsMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v wsMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *wsMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *wsMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro(l, v)
}
func easyjson8536833dDecodeDegenPkgConnectorsPintupro1(in *jlexer.Lexer, out *walletsMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
	} else {
		in.Delim('{')
		*out = make(walletsMsg)
		for !in.IsDelim('}') {
			key := string(in.String())
			in.WantColon()
			var v1 walletSnapshotMsg
			(v1).UnmarshalEasyJSON(in)
			(*out)[key] = v1
			in.WantComma()
		}
		in.Delim('}')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro1(out *jwriter.Writer, in walletsMsg) {
	if in == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
		out.RawString(`null`)
	} else {
		out.RawByte('{')
		v2First := true
		for v2Name, v2Value := range in {
			if v2First {
				v2First = false
			} else {
				out.RawByte(',')
			}
			out.String(string(v2Name))
			out.RawByte(':')
			(v2Value).MarshalEasyJSON(out)
		}
		out.RawByte('}')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v walletsMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v walletsMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *walletsMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *walletsMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro1(l, v)
}
func easyjson8536833dDecodeDegenPkgConnectorsPintupro2(in *jlexer.Lexer, out *walletSnapshotMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "balance":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Balance).UnmarshalJSON(data))
			}
		case "available":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Available).UnmarshalJSON(data))
			}
		case "order":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Order).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro2(out *jwriter.Writer, in walletSnapshotMsg) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"balance\":"
		out.RawString(prefix[1:])
		out.Raw((in.Balance).MarshalJSON())
	}
	{
		const prefix string = ",\"available\":"
		out.RawString(prefix)
		out.Raw((in.Available).MarshalJSON())
	}
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix)
		out.Raw((in.Order).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v walletSnapshotMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v walletSnapshotMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *walletSnapshotMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *walletSnapshotMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro2(l, v)
}
func easyjson8536833dDecodeDegenPkgConnectorsPintupro3(in *jlexer.Lexer, out *userOrdersMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(userOrdersMsg, 0, 0)
			} else {
				*out = userOrdersMsg{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v3 orderStatusMsg
			(v3).UnmarshalEasyJSON(in)
			*out = append(*out, v3)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro3(out *jwriter.Writer, in userOrdersMsg) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v4, v5 := range in {
			if v4 > 0 {
				out.RawByte(',')
			}
			(v5).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v userOrdersMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v userOrdersMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *userOrdersMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *userOrdersMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro3(l, v)
}
func easyjson8536833dDecodeDegenPkgConnectorsPintupro4(in *jlexer.Lexer, out *tradesMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "trades":
			if in.IsNull() {
				in.Skip()
				out.Trades = nil
			} else {
				in.Delim('[')
				if out.Trades == nil {
					if !in.IsDelim(']') {
						out.Trades = make([]struct {
							Side      string `json:"side"`
							Price     string `json:"price"`
							Size      string `json:"size"`
							Timestamp int64  `json:"timestamp"`
							Symbol    string `json:"symbol"`
						}, 0, 0)
					} else {
						out.Trades = []struct {
							Side      string `json:"side"`
							Price     string `json:"price"`
							Size      string `json:"size"`
							Timestamp int64  `json:"timestamp"`
							Symbol    string `json:"symbol"`
						}{}
					}
				} else {
					out.Trades = (out.Trades)[:0]
				}
				for !in.IsDelim(']') {
					var v6 struct {
						Side      string `json:"side"`
						Price     string `json:"price"`
						Size      string `json:"size"`
						Timestamp int64  `json:"timestamp"`
						Symbol    string `json:"symbol"`
					}
					easyjson8536833dDecode(in, &v6)
					out.Trades = append(out.Trades, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro4(out *jwriter.Writer, in tradesMsg) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"trades\":"
		out.RawString(prefix[1:])
		if in.Trades == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.Trades {
				if v7 > 0 {
					out.RawByte(',')
				}
				easyjson8536833dEncode(out, v8)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v tradesMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v tradesMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *tradesMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *tradesMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro4(l, v)
}
func easyjson8536833dDecode(in *jlexer.Lexer, out *struct {
	Side      string `json:"side"`
	Price     string `json:"price"`
	Size      string `json:"size"`
	Timestamp int64  `json:"timestamp"`
	Symbol    string `json:"symbol"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "side":
			out.Side = string(in.String())
		case "price":
			out.Price = string(in.String())
		case "size":
			out.Size = string(in.String())
		case "timestamp":
			out.Timestamp = int64(in.Int64())
		case "symbol":
			out.Symbol = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncode(out *jwriter.Writer, in struct {
	Side      string `json:"side"`
	Price     string `json:"price"`
	Size      string `json:"size"`
	Timestamp int64  `json:"timestamp"`
	Symbol    string `json:"symbol"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"side\":"
		out.RawString(prefix[1:])
		out.String(string(in.Side))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.String(string(in.Price))
	}
	{
		const prefix string = ",\"size\":"
		out.RawString(prefix)
		out.String(string(in.Size))
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.Int64(int64(in.Timestamp))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	out.RawByte('}')
}
func easyjson8536833dDecodeDegenPkgConnectorsPintupro5(in *jlexer.Lexer, out *symbolsReferenceResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "symbols":
			if in.IsNull() {
				in.Skip()
				out.Symbols = nil
			} else {
				in.Delim('[')
				if out.Symbols == nil {
					if !in.IsDelim(']') {
						out.Symbols = make([]struct {
							Symbol           string          `json:"symbol"`
							QuoteAsset       string          `json:"quote_asset"`
							BaseAsset        string          `json:"base_asset"`
							MaxSize          decimal.Decimal `json:"max_size"`
							MinSize          decimal.Decimal `json:"min_size"`
							PriceTickSize    decimal.Decimal `json:"price_tick_size"`
							QuantityTickSize decimal.Decimal `json:"quantity_tick_size"`
						}, 0, 0)
					} else {
						out.Symbols = []struct {
							Symbol           string          `json:"symbol"`
							QuoteAsset       string          `json:"quote_asset"`
							BaseAsset        string          `json:"base_asset"`
							MaxSize          decimal.Decimal `json:"max_size"`
							MinSize          decimal.Decimal `json:"min_size"`
							PriceTickSize    decimal.Decimal `json:"price_tick_size"`
							QuantityTickSize decimal.Decimal `json:"quantity_tick_size"`
						}{}
					}
				} else {
					out.Symbols = (out.Symbols)[:0]
				}
				for !in.IsDelim(']') {
					var v9 struct {
						Symbol           string          `json:"symbol"`
						QuoteAsset       string          `json:"quote_asset"`
						BaseAsset        string          `json:"base_asset"`
						MaxSize          decimal.Decimal `json:"max_size"`
						MinSize          decimal.Decimal `json:"min_size"`
						PriceTickSize    decimal.Decimal `json:"price_tick_size"`
						QuantityTickSize decimal.Decimal `json:"quantity_tick_size"`
					}
					easyjson8536833dDecode1(in, &v9)
					out.Symbols = append(out.Symbols, v9)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro5(out *jwriter.Writer, in symbolsReferenceResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbols\":"
		out.RawString(prefix[1:])
		if in.Symbols == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v10, v11 := range in.Symbols {
				if v10 > 0 {
					out.RawByte(',')
				}
				easyjson8536833dEncode1(out, v11)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v symbolsReferenceResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v symbolsReferenceResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *symbolsReferenceResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *symbolsReferenceResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro5(l, v)
}
func easyjson8536833dDecode1(in *jlexer.Lexer, out *struct {
	Symbol           string          `json:"symbol"`
	QuoteAsset       string          `json:"quote_asset"`
	BaseAsset        string          `json:"base_asset"`
	MaxSize          decimal.Decimal `json:"max_size"`
	MinSize          decimal.Decimal `json:"min_size"`
	PriceTickSize    decimal.Decimal `json:"price_tick_size"`
	QuantityTickSize decimal.Decimal `json:"quantity_tick_size"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "symbol":
			out.Symbol = string(in.String())
		case "quote_asset":
			out.QuoteAsset = string(in.String())
		case "base_asset":
			out.BaseAsset = string(in.String())
		case "max_size":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.MaxSize).UnmarshalJSON(data))
			}
		case "min_size":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.MinSize).UnmarshalJSON(data))
			}
		case "price_tick_size":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.PriceTickSize).UnmarshalJSON(data))
			}
		case "quantity_tick_size":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.QuantityTickSize).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncode1(out *jwriter.Writer, in struct {
	Symbol           string          `json:"symbol"`
	QuoteAsset       string          `json:"quote_asset"`
	BaseAsset        string          `json:"base_asset"`
	MaxSize          decimal.Decimal `json:"max_size"`
	MinSize          decimal.Decimal `json:"min_size"`
	PriceTickSize    decimal.Decimal `json:"price_tick_size"`
	QuantityTickSize decimal.Decimal `json:"quantity_tick_size"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"quote_asset\":"
		out.RawString(prefix)
		out.String(string(in.QuoteAsset))
	}
	{
		const prefix string = ",\"base_asset\":"
		out.RawString(prefix)
		out.String(string(in.BaseAsset))
	}
	{
		const prefix string = ",\"max_size\":"
		out.RawString(prefix)
		out.Raw((in.MaxSize).MarshalJSON())
	}
	{
		const prefix string = ",\"min_size\":"
		out.RawString(prefix)
		out.Raw((in.MinSize).MarshalJSON())
	}
	{
		const prefix string = ",\"price_tick_size\":"
		out.RawString(prefix)
		out.Raw((in.PriceTickSize).MarshalJSON())
	}
	{
		const prefix string = ",\"quantity_tick_size\":"
		out.RawString(prefix)
		out.Raw((in.QuantityTickSize).MarshalJSON())
	}
	out.RawByte('}')
}
func easyjson8536833dDecodeDegenPkgConnectorsPintupro6(in *jlexer.Lexer, out *responseMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "request_id":
			out.RequestID = string(in.String())
		case "timestamp":
			out.Timestamp = int64(in.Int64())
		case "method":
			out.Method = string(in.String())
		case "code":
			out.Code = int(in.Int())
		case "message":
			out.Message = string(in.String())
		case "reason":
			out.Reason = string(in.String())
		case "data":
			if m, ok := out.Data.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Data.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Data = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro6(out *jwriter.Writer, in responseMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"request_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.RequestID))
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.Int64(int64(in.Timestamp))
	}
	{
		const prefix string = ",\"method\":"
		out.RawString(prefix)
		out.String(string(in.Method))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.Int(int(in.Code))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		if m, ok := in.Data.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Data.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Data))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v responseMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v responseMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *responseMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *responseMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro6(l, v)
}
func easyjson8536833dDecodeDegenPkgConnectorsPintupro7(in *jlexer.Lexer, out *placeOrderResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "order_id":
			out.OrderID = string(in.String())
		case "client_order_id":
			out.ClientOrderID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro7(out *jwriter.Writer, in placeOrderResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"order_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.OrderID))
	}
	{
		const prefix string = ",\"client_order_id\":"
		out.RawString(prefix)
		out.String(string(in.ClientOrderID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v placeOrderResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v placeOrderResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *placeOrderResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *placeOrderResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro7(l, v)
}
func easyjson8536833dDecodeDegenPkgConnectorsPintupro8(in *jlexer.Lexer, out *placeOrderRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "symbol":
			out.Symbol = string(in.String())
		case "side":
			out.Side = string(in.String())
		case "type":
			out.Type = string(in.String())
		case "price":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Price).UnmarshalJSON(data))
			}
		case "size":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Size).UnmarshalJSON(data))
			}
		case "notional":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Notional).UnmarshalJSON(data))
			}
		case "client_order_id":
			out.ClientOrderID = string(in.String())
		case "time_in_force":
			out.TimeInForce = string(in.String())
		case "exec_inst":
			out.ExecInst = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro8(out *jwriter.Writer, in placeOrderRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"side\":"
		out.RawString(prefix)
		out.String(string(in.Side))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	if true {
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Raw((in.Price).MarshalJSON())
	}
	if true {
		const prefix string = ",\"size\":"
		out.RawString(prefix)
		out.Raw((in.Size).MarshalJSON())
	}
	if true {
		const prefix string = ",\"notional\":"
		out.RawString(prefix)
		out.Raw((in.Notional).MarshalJSON())
	}
	if in.ClientOrderID != "" {
		const prefix string = ",\"client_order_id\":"
		out.RawString(prefix)
		out.String(string(in.ClientOrderID))
	}
	if in.TimeInForce != "" {
		const prefix string = ",\"time_in_force\":"
		out.RawString(prefix)
		out.String(string(in.TimeInForce))
	}
	if in.ExecInst != "" {
		const prefix string = ",\"exec_inst\":"
		out.RawString(prefix)
		out.String(string(in.ExecInst))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v placeOrderRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v placeOrderRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *placeOrderRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *placeOrderRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro8(l, v)
}
func easyjson8536833dDecodeDegenPkgConnectorsPintupro9(in *jlexer.Lexer, out *orderStatusMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status":
			out.Status = string(in.String())
		case "symbol":
			out.Symbol = string(in.String())
		case "reason":
			out.Reason = string(in.String())
		case "type":
			out.Type = string(in.String())
		case "time_in_force":
			out.TimeInForce = string(in.String())
		case "exec_inst":
			out.ExecInst = string(in.String())
		case "side":
			out.Side = string(in.String())
		case "price":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Price).UnmarshalJSON(data))
			}
		case "size":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Size).UnmarshalJSON(data))
			}
		case "notional":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Notional).UnmarshalJSON(data))
			}
		case "cum_price":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CumPrice).UnmarshalJSON(data))
			}
		case "cum_size":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CumSize).UnmarshalJSON(data))
			}
		case "cum_value":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CumValue).UnmarshalJSON(data))
			}
		case "order_id":
			out.OrderID = string(in.String())
		case "client_order_id":
			out.ClientOrderID = string(in.String())
		case "created_at":
			out.CreatedAt = int64(in.Int64())
		case "updated_at":
			out.UpdatedAt = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro9(out *jwriter.Writer, in orderStatusMsg) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"time_in_force\":"
		out.RawString(prefix)
		out.String(string(in.TimeInForce))
	}
	{
		const prefix string = ",\"exec_inst\":"
		out.RawString(prefix)
		out.String(string(in.ExecInst))
	}
	{
		const prefix string = ",\"side\":"
		out.RawString(prefix)
		out.String(string(in.Side))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Raw((in.Price).MarshalJSON())
	}
	{
		const prefix string = ",\"size\":"
		out.RawString(prefix)
		out.Raw((in.Size).MarshalJSON())
	}
	{
		const prefix string = ",\"notional\":"
		out.RawString(prefix)
		out.Raw((in.Notional).MarshalJSON())
	}
	{
		const prefix string = ",\"cum_price\":"
		out.RawString(prefix)
		out.Raw((in.CumPrice).MarshalJSON())
	}
	{
		const prefix string = ",\"cum_size\":"
		out.RawString(prefix)
		out.Raw((in.CumSize).MarshalJSON())
	}
	{
		const prefix string = ",\"cum_value\":"
		out.RawString(prefix)
		out.Raw((in.CumValue).MarshalJSON())
	}
	{
		const prefix string = ",\"order_id\":"
		out.RawString(prefix)
		out.String(string(in.OrderID))
	}
	{
		const prefix string = ",\"client_order_id\":"
		out.RawString(prefix)
		out.String(string(in.ClientOrderID))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Int64(int64(in.CreatedAt))
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Int64(int64(in.UpdatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v orderStatusMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v orderStatusMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *orderStatusMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *orderStatusMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro9(l, v)
}
func easyjson8536833dDecodeDegenPkgConnectorsPintupro10(in *jlexer.Lexer, out *orderBookMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "symbol":
			out.Symbol = string(in.String())
		case "bids":
			if in.IsNull() {
				in.Skip()
				out.Bids = nil
			} else {
				in.Delim('[')
				if out.Bids == nil {
					if !in.IsDelim(']') {
						out.Bids = make([][]string, 0, 2)
					} else {
						out.Bids = [][]string{}
					}
				} else {
					out.Bids = (out.Bids)[:0]
				}
				for !in.IsDelim(']') {
					var v12 []string
					if in.IsNull() {
						in.Skip()
						v12 = nil
					} else {
						in.Delim('[')
						if v12 == nil {
							if !in.IsDelim(']') {
								v12 = make([]string, 0, 4)
							} else {
								v12 = []string{}
							}
						} else {
							v12 = (v12)[:0]
						}
						for !in.IsDelim(']') {
							var v13 string
							v13 = string(in.String())
							v12 = append(v12, v13)
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Bids = append(out.Bids, v12)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "asks":
			if in.IsNull() {
				in.Skip()
				out.Asks = nil
			} else {
				in.Delim('[')
				if out.Asks == nil {
					if !in.IsDelim(']') {
						out.Asks = make([][]string, 0, 2)
					} else {
						out.Asks = [][]string{}
					}
				} else {
					out.Asks = (out.Asks)[:0]
				}
				for !in.IsDelim(']') {
					var v14 []string
					if in.IsNull() {
						in.Skip()
						v14 = nil
					} else {
						in.Delim('[')
						if v14 == nil {
							if !in.IsDelim(']') {
								v14 = make([]string, 0, 4)
							} else {
								v14 = []string{}
							}
						} else {
							v14 = (v14)[:0]
						}
						for !in.IsDelim(']') {
							var v15 string
							v15 = string(in.String())
							v14 = append(v14, v15)
							in.WantComma()
						}
						in.Delim(']')
					}
					out.Asks = append(out.Asks, v14)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro10(out *jwriter.Writer, in orderBookMsg) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"bids\":"
		out.RawString(prefix)
		if in.Bids == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v16, v17 := range in.Bids {
				if v16 > 0 {
					out.RawByte(',')
				}
				if v17 == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v18, v19 := range v17 {
						if v18 > 0 {
							out.RawByte(',')
						}
						out.String(string(v19))
					}
					out.RawByte(']')
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"asks\":"
		out.RawString(prefix)
		if in.Asks == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v20, v21 := range in.Asks {
				if v20 > 0 {
					out.RawByte(',')
				}
				if v21 == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v22, v23 := range v21 {
						if v22 > 0 {
							out.RawByte(',')
						}
						out.String(string(v23))
					}
					out.RawByte(']')
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v orderBookMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v orderBookMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *orderBookMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *orderBookMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro10(l, v)
}
func easyjson8536833dDecodeDegenPkgConnectorsPintupro11(in *jlexer.Lexer, out *cancelOrderRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "symbol":
			out.Symbol = string(in.String())
		case "order_id":
			out.OrderID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro11(out *jwriter.Writer, in cancelOrderRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"order_id\":"
		out.RawString(prefix)
		out.String(string(in.OrderID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v cancelOrderRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v cancelOrderRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *cancelOrderRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *cancelOrderRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro11(l, v)
}
func easyjson8536833dDecodeDegenPkgConnectorsPintupro12(in *jlexer.Lexer, out *balanceSnapshotMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "assets":
			(out.Assets).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro12(out *jwriter.Writer, in balanceSnapshotMsg) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"assets\":"
		out.RawString(prefix[1:])
		(in.Assets).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v balanceSnapshotMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v balanceSnapshotMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *balanceSnapshotMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *balanceSnapshotMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro12(l, v)
}
func easyjson8536833dDecodeDegenPkgConnectorsPintupro13(in *jlexer.Lexer, out *assetBalanceResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "balance":
			out.Balance = string(in.String())
		case "available":
			out.Available = string(in.String())
		case "order":
			out.Order = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro13(out *jwriter.Writer, in assetBalanceResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"balance\":"
		out.RawString(prefix[1:])
		out.String(string(in.Balance))
	}
	{
		const prefix string = ",\"available\":"
		out.RawString(prefix)
		out.String(string(in.Available))
	}
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix)
		out.String(string(in.Order))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v assetBalanceResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v assetBalanceResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *assetBalanceResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *assetBalanceResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro13(l, v)
}
func easyjson8536833dDecodeDegenPkgConnectorsPintupro14(in *jlexer.Lexer, out *accountInfoResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "assets":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Assets = make(map[string]assetBalanceResponse)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v24 assetBalanceResponse
					(v24).UnmarshalEasyJSON(in)
					(out.Assets)[key] = v24
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro14(out *jwriter.Writer, in accountInfoResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"assets\":"
		out.RawString(prefix[1:])
		if in.Assets == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v25First := true
			for v25Name, v25Value := range in.Assets {
				if v25First {
					v25First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v25Name))
				out.RawByte(':')
				(v25Value).MarshalEasyJSON(out)
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v accountInfoResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v accountInfoResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *accountInfoResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *accountInfoResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro14(l, v)
}
func easyjson8536833dDecodeDegenPkgConnectorsPintupro15(in *jlexer.Lexer, out *Envelope) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "request_id":
			out.RequestID = string(in.String())
		case "timestamp":
			out.Timestamp = int64(in.Int64())
		case "method":
			out.Method = string(in.String())
		case "params":
			if m, ok := out.Params.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Params.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Params = in.Interface()
			}
		case "signature":
			out.Signature = string(in.String())
		case "api_key":
			out.APIKey = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8536833dEncodeDegenPkgConnectorsPintupro15(out *jwriter.Writer, in Envelope) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"request_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.RequestID))
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.Int64(int64(in.Timestamp))
	}
	{
		const prefix string = ",\"method\":"
		out.RawString(prefix)
		out.String(string(in.Method))
	}
	{
		const prefix string = ",\"params\":"
		out.RawString(prefix)
		if m, ok := in.Params.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Params.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Params))
		}
	}
	{
		const prefix string = ",\"signature\":"
		out.RawString(prefix)
		out.String(string(in.Signature))
	}
	{
		const prefix string = ",\"api_key\":"
		out.RawString(prefix)
		out.String(string(in.APIKey))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Envelope) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8536833dEncodeDegenPkgConnectorsPintupro15(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Envelope) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8536833dEncodeDegenPkgConnectorsPintupro15(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Envelope) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8536833dDecodeDegenPkgConnectorsPintupro15(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Envelope) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8536833dDecodeDegenPkgConnectorsPintupro15(l, v)
}
